import type { LabCategory, LabCategoryId, LabScenario } from "./types";

/**
 * Biblioteca interna de escenarios.
 *
 * Es DATA, no páginas: añadir un escenario nuevo no crea componentes nuevos.
 * La interfaz muestra solo una selección por categoría, nunca la lista entera.
 */

export const LAB_CATEGORIES: readonly LabCategory[] = [
  { id: "comercial", label: "Comercial" },
  { id: "reservas", label: "Reservas" },
  { id: "clinicas", label: "Clínicas" },
  { id: "restaurantes", label: "Restaurantes" },
  { id: "inmobiliaria", label: "Inmobiliaria" },
  { id: "profesionales", label: "Profesionales" },
  { id: "administracion", label: "Administración" },
  { id: "documentos", label: "Documentos" },
  { id: "integraciones", label: "Integraciones" },
  { id: "ia", label: "IA" },
  { id: "excepciones", label: "Excepciones" },
] as const;

export const LAB_SCENARIOS: readonly LabScenario[] = [
  // COMERCIAL
  {
    id: "comercial-nuevo-lead",
    category: "comercial",
    title: "Nuevo lead",
    intro: "Alguien pide información desde la web.",
    inputs: ["Nombre", "Email", "Mensaje"],
    flow: ["formulario", "datos", "db", "decision", "aviso", "seguimiento"],
    logic: "Si el mensaje menciona un servicio concreto, va al responsable de esa área.",
    exception: "Sin email válido no se puede responder: se pide antes de seguir.",
    outcome: "El lead llega a una persona con contexto y con fecha de seguimiento.",
    executionMode: "simulated",
  },
  {
    id: "comercial-lead-duplicado",
    category: "comercial",
    title: "Lead duplicado",
    intro: "El mismo email vuelve a escribir en pocos minutos.",
    inputs: ["Email", "Mensaje"],
    flow: ["formulario", "datos", "db", "decision"],
    logic: "Si ya existe una solicitud reciente, no se repite ninguna acción.",
    exception: "Duplicado detectado: el proceso se detiene a propósito.",
    outcome: "Nadie recibe dos avisos por lo mismo.",
    executionMode: "real",
  },
  {
    id: "comercial-lead-urgente",
    category: "comercial",
    title: "Lead urgente",
    intro: "El mensaje pide respuesta para hoy.",
    inputs: ["Mensaje", "Hora de entrada"],
    flow: ["formulario", "datos", "decision", "whatsapp", "aviso"],
    logic: "Prioridad alta: cambia el canal del aviso, no solo el texto.",
    outcome: "El aviso llega donde el equipo sí lo va a ver.",
    executionMode: "simulated",
  },
  {
    id: "comercial-fuera-horario",
    category: "comercial",
    title: "Lead fuera de horario",
    intro: "Entra una solicitud a las 23:40.",
    inputs: ["Hora de entrada"],
    flow: ["formulario", "datos", "db", "decision", "email", "seguimiento"],
    logic: "Se confirma la recepción ahora y el aviso interno se agrupa para primera hora.",
    outcome: "El cliente no se queda en silencio y nadie trabaja de madrugada.",
    executionMode: "simulated",
  },
  {
    id: "comercial-seguimiento-propuesta",
    category: "comercial",
    title: "Seguimiento de propuesta",
    intro: "Se ha enviado una propuesta hace cinco días.",
    inputs: ["Fecha de envío", "Estado"],
    flow: ["db", "decision", "email", "seguimiento"],
    logic: "Si no hay respuesta y no está descartada, se recuerda una vez.",
    outcome: "El seguimiento deja de depender de la memoria de alguien.",
    executionMode: "simulated",
  },
  {
    id: "comercial-sin-respuesta",
    category: "comercial",
    title: "Lead sin respuesta",
    intro: "Nadie ha contestado al lead en 48 horas.",
    inputs: ["Fecha de entrada"],
    flow: ["db", "decision", "aviso"],
    logic: "El proceso escala internamente antes de dar el lead por perdido.",
    exception: "Nadie ha actuado: el aviso sube de nivel.",
    outcome: "Los leads no se pierden en silencio.",
    executionMode: "simulated",
  },
  {
    id: "comercial-reactivacion",
    category: "comercial",
    title: "Reactivación",
    intro: "Un contacto de hace seis meses vuelve a visitar la web.",
    inputs: ["Histórico", "Actividad"],
    flow: ["db", "ia", "decision", "email"],
    logic: "Se retoma la conversación anterior, no se empieza de cero.",
    outcome: "El contacto recibe algo coherente con lo que ya habló.",
    executionMode: "simulated",
  },
  {
    id: "comercial-presupuesto",
    category: "comercial",
    title: "Presupuesto",
    intro: "Un cliente configura un presupuesto en la web.",
    inputs: ["Opciones elegidas", "Contacto"],
    flow: ["formulario", "datos", "db", "email", "seguimiento"],
    logic: "El documento se genera y se envía sin intervención.",
    outcome: "El cliente tiene el presupuesto en su correo al momento.",
    executionMode: "real",
  },

  // RESERVAS
  {
    id: "reservas-nueva",
    category: "reservas",
    title: "Nueva reserva",
    intro: "Alguien pide hora para un día concreto.",
    inputs: ["Fecha", "Hora", "Contacto"],
    flow: ["formulario", "datos", "db", "decision", "email", "seguimiento"],
    logic: "Si hay hueco se confirma; si no, se ofrecen alternativas.",
    exception: "Hueco ocupado: alternativas automáticas.",
    outcome: "La reserva queda cerrada o encaminada, nunca en el aire.",
    executionMode: "simulated",
  },
  {
    id: "reservas-cancelacion",
    category: "reservas",
    title: "Cancelación",
    intro: "Un cliente cancela con poca antelación.",
    inputs: ["Reserva", "Hora de cancelación"],
    flow: ["datos", "db", "decision", "aviso", "seguimiento"],
    logic: "El hueco se libera y se ofrece a quien esté en lista de espera.",
    outcome: "Una cancelación deja de ser una pérdida automática.",
    executionMode: "simulated",
  },
  {
    id: "reservas-lista-espera",
    category: "reservas",
    title: "Lista de espera",
    intro: "No hay huecos disponibles esta semana.",
    inputs: ["Preferencia horaria"],
    flow: ["formulario", "db", "decision", "seguimiento"],
    logic: "Se guarda la preferencia y se avisa en cuanto algo encaje.",
    outcome: "La demanda no se pierde por un «no hay sitio».",
    executionMode: "simulated",
  },
  {
    id: "reservas-confirmacion",
    category: "reservas",
    title: "Confirmación",
    intro: "La reserva queda cerrada.",
    inputs: ["Reserva"],
    flow: ["db", "email", "whatsapp"],
    logic: "Se confirma por el canal por el que llegó la petición.",
    outcome: "El cliente tiene por escrito día y hora.",
    executionMode: "simulated",
  },
  {
    id: "reservas-recordatorio",
    category: "reservas",
    title: "Recordatorio",
    intro: "Falta un día para la cita.",
    inputs: ["Fecha de la cita"],
    flow: ["db", "decision", "whatsapp", "seguimiento"],
    logic: "Se recuerda solo si la reserva sigue activa.",
    outcome: "Bajan las ausencias sin que nadie llame una por una.",
    executionMode: "simulated",
  },
  {
    id: "reservas-hueco-completo",
    category: "reservas",
    title: "Hueco completo",
    intro: "Dos personas piden el mismo hueco casi a la vez.",
    inputs: ["Hora", "Marca de tiempo"],
    flow: ["datos", "db", "decision", "email"],
    logic: "Gana la primera; la segunda recibe alternativas, no un error.",
    exception: "Conflicto de agenda resuelto por orden de llegada.",
    outcome: "Nadie se queda con una reserva fantasma.",
    executionMode: "simulated",
  },

  // CLÍNICAS
  {
    id: "clinicas-primera-cita",
    category: "clinicas",
    title: "Primera cita",
    intro: "Una paciente pide una primera consulta.",
    inputs: ["Motivo", "Franja preferida"],
    flow: ["formulario", "datos", "db", "decision", "aviso", "seguimiento"],
    logic: "Una primera consulta ocupa más tiempo: no cabe en cualquier hueco.",
    exception: "Motivo poco claro: revisión humana antes de confirmar.",
    outcome: "La agenda se llena sin descuadrarse.",
    executionMode: "simulated",
  },
  {
    id: "clinicas-recordatorio",
    category: "clinicas",
    title: "Recordatorio de cita",
    intro: "La cita es mañana por la tarde.",
    inputs: ["Cita"],
    flow: ["db", "decision", "whatsapp"],
    logic: "Se recuerda con antelación suficiente para poder reasignar el hueco.",
    outcome: "Menos ausencias y huecos recuperables.",
    executionMode: "simulated",
  },
  {
    id: "clinicas-cancelacion",
    category: "clinicas",
    title: "Cancelación",
    intro: "El paciente cancela la víspera.",
    inputs: ["Cita", "Motivo"],
    flow: ["datos", "db", "decision", "aviso", "seguimiento"],
    logic: "Se libera el hueco y se ofrece a la lista de espera.",
    outcome: "El hueco no se queda vacío por defecto.",
    executionMode: "simulated",
  },
  {
    id: "clinicas-documentacion",
    category: "clinicas",
    title: "Documentación previa",
    intro: "La consulta necesita un consentimiento firmado.",
    inputs: ["Tipo de consulta"],
    flow: ["db", "decision", "email", "seguimiento"],
    logic: "Si falta el documento, se pide y se comprueba antes de la cita.",
    exception: "Documento no devuelto: aviso interno el día anterior.",
    outcome: "La consulta empieza con todo en regla.",
    executionMode: "simulated",
  },
  {
    id: "clinicas-revision-humana",
    category: "clinicas",
    title: "Revisión humana",
    intro: "El caso no encaja en ninguna categoría prevista.",
    inputs: ["Motivo libre"],
    flow: ["datos", "ia", "decision", "aviso"],
    logic: "Cuando el criterio importa, el proceso para y avisa a una persona.",
    exception: "Fuera de catálogo: intervención humana con contexto reunido.",
    outcome: "La persona decide, pero sin tener que investigar desde cero.",
    executionMode: "simulated",
  },

  // RESTAURANTES
  {
    id: "restaurantes-reserva",
    category: "restaurantes",
    title: "Reserva de mesa",
    intro: "Piden mesa para seis el viernes.",
    inputs: ["Comensales", "Fecha", "Turno"],
    flow: ["formulario", "datos", "db", "decision", "whatsapp"],
    logic: "El número de comensales decide si se confirma o se revisa.",
    outcome: "El turno se organiza sin llamadas cruzadas.",
    executionMode: "simulated",
  },
  {
    id: "restaurantes-cancelacion",
    category: "restaurantes",
    title: "Cancelación",
    intro: "Cancelan una mesa grande dos horas antes.",
    inputs: ["Reserva"],
    flow: ["datos", "db", "decision", "aviso"],
    logic: "Se libera la mesa y se avisa a sala en el momento.",
    outcome: "La sala trabaja con información actualizada.",
    executionMode: "simulated",
  },
  {
    id: "restaurantes-lista-espera",
    category: "restaurantes",
    title: "Lista de espera",
    intro: "El turno está completo.",
    inputs: ["Contacto", "Turno deseado"],
    flow: ["formulario", "db", "decision", "whatsapp"],
    logic: "Si se libera una mesa, se avisa por orden.",
    outcome: "Las cancelaciones se reaprovechan solas.",
    executionMode: "simulated",
  },
  {
    id: "restaurantes-pedido",
    category: "restaurantes",
    title: "Pedido para recoger",
    intro: "Entra un pedido desde la web.",
    inputs: ["Productos", "Hora de recogida"],
    flow: ["formulario", "datos", "db", "aviso", "seguimiento"],
    logic: "El pedido llega a cocina con la hora ya calculada.",
    outcome: "Cocina no depende de que alguien mire el móvil.",
    executionMode: "simulated",
  },
  {
    id: "restaurantes-incidencia",
    category: "restaurantes",
    title: "Incidencia",
    intro: "Un cliente reporta un problema con su pedido.",
    inputs: ["Pedido", "Descripción"],
    flow: ["formulario", "datos", "decision", "aviso"],
    logic: "Las incidencias saltan la cola y van directas a encargado.",
    exception: "Reclamación: siempre pasa por una persona.",
    outcome: "El problema se resuelve el mismo día.",
    executionMode: "simulated",
  },
  {
    id: "restaurantes-confirmacion",
    category: "restaurantes",
    title: "Confirmación del día",
    intro: "Es la mañana del día de la reserva.",
    inputs: ["Reservas del día"],
    flow: ["db", "decision", "whatsapp", "seguimiento"],
    logic: "Se pide confirmación y quien no responde libera la mesa.",
    outcome: "Menos mesas vacías reservadas.",
    executionMode: "simulated",
  },

  // INMOBILIARIA
  {
    id: "inmobiliaria-interesado",
    category: "inmobiliaria",
    title: "Nuevo interesado",
    intro: "Alguien pregunta por un piso concreto.",
    inputs: ["Referencia", "Contacto"],
    flow: ["formulario", "datos", "db", "decision", "aviso", "seguimiento"],
    logic: "La consulta va al agente que lleva esa propiedad.",
    outcome: "El interesado habla con quien conoce el inmueble.",
    executionMode: "simulated",
  },
  {
    id: "inmobiliaria-visita",
    category: "inmobiliaria",
    title: "Visita",
    intro: "Piden ver la vivienda este sábado.",
    inputs: ["Franja", "Referencia"],
    flow: ["formulario", "db", "decision", "email", "seguimiento"],
    logic: "Se comprueba la agenda del agente antes de confirmar nada.",
    outcome: "No se prometen visitas imposibles.",
    executionMode: "simulated",
  },
  {
    id: "inmobiliaria-nueva-propiedad",
    category: "inmobiliaria",
    title: "Nueva propiedad",
    intro: "Se da de alta un inmueble.",
    inputs: ["Ficha", "Fotos"],
    flow: ["datos", "db", "decision", "email"],
    logic: "Se avisa a los interesados cuyo perfil encaja.",
    outcome: "La cartera se mueve sin repasar listas a mano.",
    executionMode: "simulated",
  },
  {
    id: "inmobiliaria-seguimiento",
    category: "inmobiliaria",
    title: "Seguimiento tras visita",
    intro: "Han pasado tres días desde la visita.",
    inputs: ["Visita", "Estado"],
    flow: ["db", "decision", "email", "seguimiento"],
    logic: "Se pregunta una vez y se registra la respuesta.",
    outcome: "El agente sabe qué operaciones siguen vivas.",
    executionMode: "simulated",
  },
  {
    id: "inmobiliaria-match",
    category: "inmobiliaria",
    title: "Match comprador / propiedad",
    intro: "Entra una propiedad que encaja con una búsqueda guardada.",
    inputs: ["Criterios guardados", "Ficha"],
    flow: ["db", "ia", "decision", "email"],
    logic: "Se cruzan criterios y solo se avisa cuando el encaje es real.",
    outcome: "Menos avisos y más relevantes.",
    executionMode: "simulated",
  },

  // PROFESIONALES
  {
    id: "profesionales-consulta",
    category: "profesionales",
    title: "Consulta inicial",
    intro: "Un cliente potencial describe su caso.",
    inputs: ["Descripción"],
    flow: ["formulario", "datos", "db", "decision", "aviso"],
    logic: "El caso se dirige al área que corresponde.",
    outcome: "La consulta llega al profesional adecuado a la primera.",
    executionMode: "simulated",
  },
  {
    id: "profesionales-clasificacion",
    category: "profesionales",
    title: "Clasificación de casos",
    intro: "Llegan consultas de temas muy distintos.",
    inputs: ["Texto libre"],
    flow: ["datos", "ia", "decision", "db"],
    logic: "Se propone una categoría y una persona la confirma.",
    outcome: "El buzón deja de ser un montón indiferenciado.",
    executionMode: "simulated",
  },
  {
    id: "profesionales-documentacion",
    category: "profesionales",
    title: "Documentación pendiente",
    intro: "Falta documentación para avanzar en el expediente.",
    inputs: ["Checklist"],
    flow: ["db", "decision", "email", "seguimiento"],
    logic: "Se pide lo que falta y se recuerda hasta que llega.",
    exception: "Documento no recibido tras dos avisos: pasa a persona.",
    outcome: "Los expedientes no se paran por un papel.",
    executionMode: "simulated",
  },
  {
    id: "profesionales-seguimiento",
    category: "profesionales",
    title: "Seguimiento de expediente",
    intro: "El expediente lleva dos semanas sin movimiento.",
    inputs: ["Última actividad"],
    flow: ["db", "decision", "aviso"],
    logic: "El proceso detecta la inactividad antes que el cliente.",
    outcome: "Nada se queda olvidado en un cajón.",
    executionMode: "simulated",
  },
  {
    id: "profesionales-escalado",
    category: "profesionales",
    title: "Escalado",
    intro: "El caso supera lo que el proceso puede resolver.",
    inputs: ["Señales de complejidad"],
    flow: ["datos", "decision", "aviso"],
    logic: "Automatizar también significa saber cuándo parar.",
    exception: "Complejidad detectada: intervención humana.",
    outcome: "La persona entra con el caso ya preparado.",
    executionMode: "simulated",
  },

  // ADMINISTRACIÓN
  {
    id: "administracion-factura",
    category: "administracion",
    title: "Factura recibida",
    intro: "Llega una factura al correo.",
    inputs: ["PDF", "Remitente"],
    flow: ["datos", "ia", "db", "decision", "aviso"],
    logic: "Se extraen importe y fecha, y se avisa si algo no cuadra.",
    outcome: "La factura queda registrada sin teclear nada.",
    executionMode: "simulated",
  },
  {
    id: "administracion-documento-pendiente",
    category: "administracion",
    title: "Documento pendiente",
    intro: "Un cliente no ha enviado lo que se le pidió.",
    inputs: ["Checklist", "Fecha límite"],
    flow: ["db", "decision", "email", "seguimiento"],
    logic: "Se recuerda antes de la fecha límite, no después.",
    outcome: "Menos prisas de última hora.",
    executionMode: "simulated",
  },
  {
    id: "administracion-datos-duplicados",
    category: "administracion",
    title: "Datos duplicados",
    intro: "El mismo cliente aparece dos veces.",
    inputs: ["Registros"],
    flow: ["db", "decision", "aviso"],
    logic: "Se marca el duplicado y no se fusiona nada sin revisión.",
    exception: "Duplicado detectado: decisión humana.",
    outcome: "La base de datos no se degrada sola.",
    executionMode: "simulated",
  },
  {
    id: "administracion-informe",
    category: "administracion",
    title: "Informe periódico",
    intro: "Es el primer día del mes.",
    inputs: ["Datos del mes"],
    flow: ["db", "datos", "email", "seguimiento"],
    logic: "El informe se genera y se envía solo.",
    outcome: "Nadie dedica una mañana a copiar datos.",
    executionMode: "simulated",
  },
  {
    id: "administracion-formulario-interno",
    category: "administracion",
    title: "Formulario interno",
    intro: "Un compañero solicita material.",
    inputs: ["Solicitud"],
    flow: ["formulario", "datos", "db", "decision", "aviso"],
    logic: "Por encima de cierto importe requiere aprobación.",
    outcome: "Las peticiones internas dejan de ir por chat.",
    executionMode: "simulated",
  },

  // DOCUMENTOS
  {
    id: "documentos-formulario",
    category: "documentos",
    title: "Formulario → documento",
    intro: "Un formulario tiene que convertirse en un documento con formato.",
    inputs: ["Respuestas"],
    flow: ["formulario", "datos", "db", "email"],
    logic: "Los datos se colocan en la plantilla sin copiar y pegar.",
    outcome: "El documento sale igual siempre.",
    executionMode: "simulated",
  },
  {
    id: "documentos-presupuesto-pdf",
    category: "documentos",
    title: "Presupuesto → PDF",
    intro: "El cliente cierra la configuración de su presupuesto.",
    inputs: ["Opciones", "Contacto"],
    flow: ["formulario", "datos", "email"],
    logic: "El PDF se genera en el servidor y viaja adjunto al email.",
    outcome: "El cliente recibe su presupuesto al instante.",
    executionMode: "real",
  },
  {
    id: "documentos-onboarding",
    category: "documentos",
    title: "Onboarding",
    intro: "Entra un cliente nuevo.",
    inputs: ["Datos del cliente"],
    flow: ["datos", "db", "email", "seguimiento"],
    logic: "Se envía la documentación inicial y se comprueba que se devuelve.",
    outcome: "Todos los clientes empiezan igual de bien.",
    executionMode: "simulated",
  },
  {
    id: "documentos-documentacion",
    category: "documentos",
    title: "Documentación de proyecto",
    intro: "El proyecto cambia de fase.",
    inputs: ["Estado"],
    flow: ["db", "decision", "email"],
    logic: "Cada fase envía la documentación que le corresponde.",
    outcome: "El cliente sabe siempre en qué punto está.",
    executionMode: "simulated",
  },

  // INTEGRACIONES
  {
    id: "integraciones-web-crm",
    category: "integraciones",
    title: "Web → CRM",
    intro: "Una solicitud tiene que aparecer en el CRM.",
    inputs: ["Formulario"],
    flow: ["formulario", "datos", "crm", "aviso"],
    logic: "La ficha se crea con los campos ya normalizados.",
    exception: "Si el CRM no responde, la solicitud no se pierde: se reintenta.",
    outcome: "Nadie vuelve a teclear lo que ya estaba escrito.",
    executionMode: "simulated",
  },
  {
    id: "integraciones-web-db",
    category: "integraciones",
    title: "Web → base de datos",
    intro: "Todo lo que entra debe quedar registrado.",
    inputs: ["Formulario"],
    flow: ["formulario", "datos", "db"],
    logic: "Primero registrar, después actuar.",
    outcome: "Existe un histórico consultable.",
    executionMode: "simulated",
  },
  {
    id: "integraciones-reserva-calendario",
    category: "integraciones",
    title: "Reserva → calendario",
    intro: "Una reserva confirmada tiene que ocupar la agenda.",
    inputs: ["Reserva"],
    flow: ["db", "decision", "aviso"],
    logic: "El hueco se bloquea en el momento de confirmar.",
    exception: "Sin integración de calendario, el paso queda representado.",
    outcome: "La agenda refleja la realidad.",
    executionMode: "simulated",
  },
  {
    id: "integraciones-formulario-email",
    category: "integraciones",
    title: "Formulario → email",
    intro: "Una solicitud debe avisar a una persona concreta.",
    inputs: ["Formulario"],
    flow: ["formulario", "datos", "email"],
    logic: "El destinatario depende del contenido, no es fijo.",
    outcome: "El aviso llega a quien tiene que actuar.",
    executionMode: "real",
  },
  {
    id: "integraciones-pago-registro",
    category: "integraciones",
    title: "Pago → registro",
    intro: "Se confirma un pago.",
    inputs: ["Referencia de pago"],
    flow: ["datos", "db", "email"],
    logic: "El pago actualiza el estado del pedido y dispara el justificante.",
    outcome: "Contabilidad y cliente ven lo mismo.",
    executionMode: "simulated",
  },
  {
    id: "integraciones-crm-seguimiento",
    category: "integraciones",
    title: "CRM → seguimiento",
    intro: "Una oportunidad lleva días parada.",
    inputs: ["Estado en CRM"],
    flow: ["crm", "decision", "aviso", "seguimiento"],
    logic: "El CRM deja de ser un archivo y empieza a avisar.",
    outcome: "El pipeline se mueve.",
    executionMode: "simulated",
  },

  // IA
  {
    id: "ia-clasificacion",
    category: "ia",
    title: "Clasificación",
    intro: "Llegan mensajes escritos en lenguaje libre.",
    inputs: ["Texto"],
    flow: ["datos", "ia", "decision", "db"],
    logic: "La IA propone categoría; el proceso decide qué hacer con ella.",
    outcome: "Cada mensaje entra por la puerta correcta.",
    executionMode: "simulated",
  },
  {
    id: "ia-extraccion",
    category: "ia",
    title: "Extracción de datos",
    intro: "Los datos vienen dentro de un documento.",
    inputs: ["PDF o imagen"],
    flow: ["datos", "ia", "db", "decision"],
    logic: "Se extraen campos y se marcan los que no son fiables.",
    exception: "Confianza baja: revisión humana del campo.",
    outcome: "Menos tecleo y errores localizados.",
    executionMode: "simulated",
  },
  {
    id: "ia-resumen",
    category: "ia",
    title: "Resumen",
    intro: "Una conversación larga tiene que caber en un aviso.",
    inputs: ["Historial"],
    flow: ["db", "ia", "aviso"],
    logic: "El aviso incluye el contexto, no solo el último mensaje.",
    outcome: "Quien recibe el aviso entiende el caso sin abrir nada más.",
    executionMode: "simulated",
  },
  {
    id: "ia-intencion",
    category: "ia",
    title: "Intención",
    intro: "El mismo formulario recibe consultas y reclamaciones.",
    inputs: ["Texto"],
    flow: ["formulario", "ia", "decision", "aviso"],
    logic: "Una reclamación no puede tratarse como una consulta.",
    outcome: "La urgencia se detecta antes de que escale.",
    executionMode: "simulated",
  },
  {
    id: "ia-routing",
    category: "ia",
    title: "Routing",
    intro: "Hay varios equipos y un solo buzón.",
    inputs: ["Texto", "Reglas de equipo"],
    flow: ["datos", "ia", "decision", "aviso"],
    logic: "El destinatario se calcula, no se reparte a mano.",
    outcome: "Cada equipo ve solo lo suyo.",
    executionMode: "simulated",
  },

  // EXCEPCIONES
  {
    id: "excepciones-datos-incompletos",
    category: "excepciones",
    title: "Datos incompletos",
    intro: "Falta un dato imprescindible para continuar.",
    inputs: ["Formulario parcial"],
    flow: ["formulario", "datos", "decision", "email"],
    logic: "Se pide lo que falta en lugar de seguir con un hueco.",
    exception: "Campo obligatorio ausente.",
    outcome: "El proceso no arrastra errores.",
    executionMode: "simulated",
  },
  {
    id: "excepciones-duplicado",
    category: "excepciones",
    title: "Duplicado",
    intro: "La misma solicitud entra dos veces.",
    inputs: ["Email", "Marca de tiempo"],
    flow: ["datos", "db", "decision"],
    logic: "Si ya existe algo reciente, no se repite ninguna acción real.",
    exception: "Duplicado: el proceso se detiene a propósito.",
    outcome: "Ni dos emails, ni dos fichas, ni dos avisos.",
    executionMode: "real",
  },
  {
    id: "excepciones-integracion-fallida",
    category: "excepciones",
    title: "Integración fallida",
    intro: "El sistema externo devuelve un error.",
    inputs: ["Respuesta del servicio"],
    flow: ["datos", "decision", "aviso", "seguimiento"],
    logic: "Se reintenta un número limitado de veces y luego se avisa.",
    exception: "Servicio externo no disponible.",
    outcome: "El fallo se detecta antes que el cliente.",
    executionMode: "simulated",
  },
  {
    id: "excepciones-servicio-caido",
    category: "excepciones",
    title: "Servicio no disponible",
    intro: "Un proveedor está caído durante horas.",
    inputs: ["Estado del servicio"],
    flow: ["datos", "db", "decision", "aviso"],
    logic: "Las solicitudes se guardan en cola en vez de perderse.",
    exception: "Caída prolongada: cola y aviso interno.",
    outcome: "Cuando vuelve el servicio, no falta nada.",
    executionMode: "simulated",
  },
  {
    id: "excepciones-contradiccion",
    category: "excepciones",
    title: "Contradicción",
    intro: "Los datos recibidos se contradicen entre sí.",
    inputs: ["Campos en conflicto"],
    flow: ["datos", "decision", "aviso"],
    logic: "Cuando dos reglas chocan, decide una persona.",
    exception: "Conflicto de reglas: intervención humana.",
    outcome: "El proceso no elige al azar.",
    executionMode: "simulated",
  },
  {
    id: "excepciones-fuera-horario",
    category: "excepciones",
    title: "Fuera de horario",
    intro: "La solicitud entra de madrugada.",
    inputs: ["Hora"],
    flow: ["formulario", "decision", "email", "seguimiento"],
    logic: "Se responde ahora y se actúa cuando toca.",
    outcome: "El cliente no percibe el horario.",
    executionMode: "simulated",
  },
  {
    id: "excepciones-urgente",
    category: "excepciones",
    title: "Urgente",
    intro: "El mensaje pide una respuesta inmediata.",
    inputs: ["Texto"],
    flow: ["datos", "decision", "whatsapp", "aviso"],
    logic: "La urgencia cambia el canal y el destinatario.",
    exception: "Prioridad alta: se salta la cola.",
    outcome: "Lo urgente no espera al lunes.",
    executionMode: "simulated",
  },
  {
    id: "excepciones-intervencion-humana",
    category: "excepciones",
    title: "Intervención humana",
    intro: "El caso necesita criterio, no reglas.",
    inputs: ["Contexto completo"],
    flow: ["datos", "db", "decision", "aviso"],
    logic: "El proceso para y entrega el caso preparado a una persona.",
    exception: "No resoluble automáticamente.",
    outcome: "Las personas se reservan para lo que de verdad lo necesita.",
    executionMode: "simulated",
  },
] as const;

export function getScenariosByCategory(
  category: LabCategoryId,
): readonly LabScenario[] {
  return LAB_SCENARIOS.filter((scenario) => scenario.category === category);
}

export function getScenarioById(id: string): LabScenario | undefined {
  return LAB_SCENARIOS.find((scenario) => scenario.id === id);
}

export const LAB_SCENARIO_COUNT = LAB_SCENARIOS.length;
